export const taskData = [
    { name: "Dự án A", completed: 20, totalTasks: 10 },
    { name: "Dự án B", completed: 35, totalTasks: 10 },
    { name: "Dự án C", completed: 15, totalTasks: 10 },
    { name: "Dự án D", completed: 40, totalTasks: 20 },
    { name: "Dự án E", completed: 25, totalTasks: 10 },
    { name: "Dự án F", completed: 30, totalTasks: 20 },
    { name: "Dự án G", completed: 10, totalTasks: 10 },
    { name: "Dự án H", completed: 50, totalTasks: 20 },
    { name: "Dự án J", completed: 20, totalTasks: 10 },
    { name: "Dự án K", completed: 35, totalTasks: 10 },
    { name: "Dự án L", completed: 15, totalTasks: 10 },
    { name: "Dự án M", completed: 40, totalTasks: 20 },
    { name: "Dự án N", completed: 25, totalTasks: 10 },
    { name: "Dự án V", completed: 30, totalTasks: 20 },
    { name: "Dự án U", completed: 10, totalTasks: 10 },
    { name: "Dự án I", completed: 50, totalTasks: 20 },
    { name: "Dự án M", completed: 40, totalTasks: 20 },
    { name: "Dự án N", completed: 25, totalTasks: 10 },
    { name: "Dự án V", completed: 30, totalTasks: 20 },
    { name: "Dự án U", completed: 10, totalTasks: 10 },
    { name: "Dự án I", completed: 50, totalTasks: 20 },
    { name: "Dự án M", completed: 40, totalTasks: 20 },
    { name: "Dự án N", completed: 25, totalTasks: 10 },
    { name: "Dự án V", completed: 30, totalTasks: 20 },
    { name: "Dự án U", completed: 10, totalTasks: 10 },
    { name: "Dự án I", completed: 50, totalTasks: 20 },
  ];
  
  export const timeData = [
    { name: "Dự án A", actualTime: 25, plannedTime: 10 },
    { name: "Dự án B", actualTime: 40, plannedTime: 15 },
    { name: "Dự án C", actualTime: 20, plannedTime: 12 },
    { name: "Dự án D", actualTime: 45, plannedTime: 20 },
    { name: "Dự án E", actualTime: 30, plannedTime: 18 },
    { name: "Dự án F", actualTime: 35, plannedTime: 25 },
    { name: "Dự án G", actualTime: 15, plannedTime: 10 },
    { name: "Dự án H", actualTime: 55, plannedTime: 30 },
    { name: "Dự án I", actualTime: 28, plannedTime: 15 },
    { name: "Dự án J", actualTime: 42, plannedTime: 22 },
    { name: "Dự án K", actualTime: 33, plannedTime: 20 },
    { name: "Dự án L", actualTime: 38, plannedTime: 25 },
    { name: "Dự án M", actualTime: 22, plannedTime: 12 },
    { name: "Dự án N", actualTime: 48, plannedTime: 28 },
    { name: "Dự án O", actualTime: 18, plannedTime: 15 },
    { name: "Dự án P", actualTime: 50, plannedTime: 35 },
  ];
  
  export const projectTaskData = [
    { name: "Dự án A", new: 10, assigned: 15, inProgress: 20, close: 5 },
    { name: "Dự án B", new: 15, assigned: 20, inProgress: 25, close: 10 },
    { name: "Dự án C", new: 5, assigned: 10, inProgress: 15, close: 5 },
    { name: "Dự án D", new: 20, assigned: 25, inProgress: 30, close: 15 },
    { name: "Dự án E", new: 12, assigned: 18, inProgress: 22, close: 8 },
    { name: "Dự án F", new: 18, assigned: 22, inProgress: 28, close: 12 },
    { name: "Dự án G", new: 8, assigned: 12, inProgress: 18, close: 6 },
    { name: "Dự án H", new: 25, assigned: 30, inProgress: 35, close: 20 },
    { name: "Dự án I", new: 14, assigned: 19, inProgress: 23, close: 9 },
    { name: "Dự án J", new: 22, assigned: 26, inProgress: 32, close: 16 },
    { name: "Dự án K", new: 7, assigned: 13, inProgress: 17, close: 7 },
    { name: "Dự án L", new: 16, assigned: 21, inProgress: 27, close: 11 },
    { name: "Dự án M", new: 11, assigned: 16, inProgress: 21, close: 7 },
    { name: "Dự án N", new: 19, assigned: 24, inProgress: 29, close: 13 },
    { name: "Dự án O", new: 9, assigned: 14, inProgress: 19, close: 8 },
    { name: "Dự án P", new: 23, assigned: 28, inProgress: 33, close: 18 },
  ];
  
  export const personnelData = [
    { name: "Dự án A", PM: 5, BA: 8, Dev: 15, Tester: 5 },
    { name: "Dự án B", PM: 4, BA: 7, Dev: 18, Tester: 6 },
    { name: "Dự án C", PM: 3, BA: 6, Dev: 20, Tester: 5 },
    { name: "Dự án D", PM: 4, BA: 5, Dev: 12, Tester: 3 },
    { name: "Dự án E", PM: 3, BA: 4, Dev: 10, Tester: 2 },
    { name: "Dự án F", PM: 4, BA: 5, Dev: 12, Tester: 3 },
    { name: "Dự án G", PM: 2, BA: 3, Dev: 8, Tester: 2 },
    { name: "Dự án H", PM: 5, BA: 7, Dev: 20, Tester: 8 },
    { name: "Dự án I", PM: 4, BA: 6, Dev: 15, Tester: 5 },
    { name: "Dự án J", PM: 3, BA: 5, Dev: 13, Tester: 4 },
    { name: "Dự án K", PM: 2, BA: 4, Dev: 10, Tester: 3 },
    { name: "Dự án L", PM: 4, BA: 6, Dev: 16, Tester: 6 },
    { name: "Dự án M", PM: 3, BA: 5, Dev: 14, Tester: 5 },
    { name: "Dự án N", PM: 4, BA: 6, Dev: 18, Tester: 7 },
    { name: "Dự án O", PM: 3, BA: 4, Dev: 12, Tester: 4 },
    { name: "Dự án P", PM: 5, BA: 7, Dev: 19, Tester: 6 },
  ];
  
  export const bugData = [
    { name: "Dự án A", New: 5, Assigned: 8, Resolved: 12, Close: 3 },
    { name: "Dự án B", New: 6, Assigned: 9, Resolved: 14, Close: 4 },
    { name: "Dự án C", New: 4, Assigned: 7, Resolved: 13, Close: 5 },
    { name: "Dự án D", New: 7, Assigned: 10, Resolved: 15, Close: 6 },
    { name: "Dự án E", New: 3, Assigned: 5, Resolved: 10, Close: 2 },
    { name: "Dự án F", New: 5, Assigned: 8, Resolved: 12, Close: 4 },
    { name: "Dự án G", New: 2, Assigned: 4, Resolved: 8, Close: 2 },
    { name: "Dự án H", New: 8, Assigned: 11, Resolved: 20, Close: 7 },
    { name: "Dự án I", New: 6, Assigned: 9, Resolved: 16, Close: 5 },
    { name: "Dự án J", New: 7, Assigned: 10, Resolved: 18, Close: 6 },
    { name: "Dự án K", New: 4, Assigned: 6, Resolved: 12, Close: 3 },
    { name: "Dự án L", New: 6, Assigned: 9, Resolved: 15, Close: 5 },
    { name: "Dự án M", New: 5, Assigned: 7, Resolved: 13, Close: 4 },
    { name: "Dự án N", New: 7, Assigned: 10, Resolved: 17, Close: 6 },
    { name: "Dự án O", New: 3, Assigned: 5, Resolved: 9, Close: 2 },
    { name: "Dự án P", New: 6, Assigned: 8, Resolved: 14, Close: 4 },
  ];
  
  export const supportTicketData = [
    { name: "Dự án A", New: 4, Resolved: 7, Close: 2 },
    { name: "Dự án B", New: 5, Resolved: 9, Close: 3 },
    { name: "Dự án C", New: 3, Resolved: 8, Close: 2 },
    { name: "Dự án D", New: 6, Resolved: 10, Close: 4 },
    { name: "Dự án E", New: 2, Resolved: 6, Close: 2 },
    { name: "Dự án F", New: 4, Resolved: 7, Close: 2 },
    { name: "Dự án G", New: 1, Resolved: 5, Close: 1 },
    { name: "Dự án H", New: 5, Resolved: 10, Close: 3 },
    { name: "Dự án I", New: 4, Resolved: 8, Close: 3 },
    { name: "Dự án J", New: 5, Resolved: 9, Close: 3 },
    { name: "Dự án K", New: 2, Resolved: 6, Close: 2 },
    { name: "Dự án L", New: 4, Resolved: 8, Close: 3 },
    { name: "Dự án M", New: 3, Resolved: 7, Close: 2 },
    { name: "Dự án N", New: 4, Resolved: 8, Close: 3 },
    { name: "Dự án O", New: 2, Resolved: 5, Close: 2 },
    { name: "Dự án P", New: 3, Resolved: 7, Close: 2 },
  ];